### ISSUE TITLE
Compiler Error on XCode 8

### ISSUE THREAD

**Issue by jkebeck** [Microsoft/Loop-Sample-Trips-IOS#12]
/.../Loop-Sample-Trips-IOS/LoopTripIOS/TripRepository.swift:27:8: **Module file was created by an older version of the compiler**; rebuild 'LoopSDK' and try again: /.../Loop-Sample-Trips-IOS/Carthage/Build/iOS/LoopSDK.framework/Modules/LoopSDK.swiftmodule/arm64.swiftmodule

This seems to be a limitation in XCode 8 but it would be great to be able to run it on the latest and greatest: https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html
"The version of Swift 2 (2.3) used in Xcode 8 is very close to the version used in Xcode 7.3.1. However, it has been updated for the newer SDKs, and therefore is not compatible with Swift frameworks compiled in Xcode 7.3.1. Distributing binary Swift frameworks remains unsupported in Xcode 8. (25680392)"

**Comment by sseiber** [comment]
Hi @jkebeck we've updated our tools after the release of iOS 10 last week and we're migrating the SDK framework and sample apps right now. Look for PR today or tomorrow into the develop branch.

**Comment by sseiber** [comment]
@jkebeck you can sync up to the develop branch now and test out the Swift3 build.
